### PR TITLE
Perpare Stoneboard for running in Docker

### PR DESCRIPTION
**Pull request by androa**
This PR adds a Dockerfile for running Stoneboard in a minimal Docker container and docker-compose.yml for convenience.

### CODE REVIEW

**Comment by mateusz-fiolka** [comment]
@androa Looks legit 👍

**Comment by hnrc** [comment]
Beautiful 🙇

**Comment by hnrc** [comment]
@androa We're closing in on the 1-year anniversary of this pull request, is it something you feel deserve a merge?

**Comment by androa** [comment]
This should be good to go :) Still. 2 years later :D

**Pull request merged**
